# Generated by Django 4.0.8 on 2023-01-15 01:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('club_name', models.CharField(max_length=200)),
                ('club_address_number', models.CharField(max_length=200)),
                ('club_address_street', models.CharField(max_length=200)),
                ('club_address_city', models.CharField(max_length=200)),
                ('club_address_postcode', models.CharField(max_length=200)),
                ('club_tphone', models.IntegerField()),
                ('club_phone', models.IntegerField()),
                ('emp_email', models.CharField(max_length=20)),
                ('rep_first_name', models.CharField(max_length=200)),
                ('rep_last_name', models.CharField(max_length=200)),
                ('rep_dob', models.DateField()),
            ],
        ),
    ]
