# Generated by Django 4.0.8 on 2023-01-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_manager', '0004_alter_club_club_address_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='club',
            name='club_tphone',
            field=models.IntegerField(),
        ),
    ]
