version: '3'
services:
  mongo:
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - '27017:27017'
  web:
    build: .
    restart: always
    ports:
      - '8000:8000'
    environment:
      MONGO_HOST: uweflix.l8xahep.mongodb.net
      MONGO_PORT: 27017
      MONGO_DB: test
      MONGO_USER: daniel2fernandes
      MONGO_PASSWORD: skelJ6UzCVlG36Ei
